### ISSUE TITLE
Define currencies in terms of union type

### ISSUE THREAD

**Issue by 3noch** [chordify/currency-codes#2]
Since you already have `Alpha`, you could write a single function (maybe `fromAlpha`) which defines all currencies as a `case` over all `Alpha`s. Then `currencies` becomes `fromAlpha <$> [minBound..maxBound]` and each currency function is either unnecessary or trivial (e.g. `usd = fromAlpha USD`).

**Comment by KtorZ** [comment]
This. I like. 

Thanks for the suggestion. I wanted to rework a bit the implementation anyway (noticed that compilation & runtime can be rather slow because of the default `Read` instance, writing it "by hand" speeds up things a lot. It seems that GHC doesn't like much big ADTs like this).

**Comment by KtorZ** [comment]
Closed with eca59c3d2fb6f0929bc16fc12e7e26c6b16c9709 :+1:

**Comment by 3noch** [comment]
Cool!
